### ISSUE TITLE
Sponsor's logos on the homepage

### ISSUE THREAD

**Issue by myles** [pyconca/2016-web#6]
The sponsor's logos should be displayed (below the fold) on the homepage of the website.

**Comment by myles** [comment]
We will need a new field in the sponsors.json file for the smaller, gray-scale versions of the logos

**Comment by myles** [comment]
I was thinking we could grey-scale it with CSS operator [filter](https://developer.mozilla.org/en/docs/Web/CSS/filter) like this:

``` scss
img {
  filter: grayscale(50%);

  &:hover {
    filter: grayscale(0);
}
```
